from docx import Document
from docx.shared import Inches
import pyttsx3

document = Document()

# Personal Details

document.add_picture("fayazz.jpg", width=Inches(1.0))
pyttsx3.speak("what is your name")
name = input("what is your name")
pyttsx3.speak("what is your phone number")
phone_number = input("what is your phone number")
pyttsx3.speak("enter your E-mail")
email = input("enter your E-mail")
document.add_paragraph(name + "\n" + phone_number + "\n" + email)
document.add_heading("About me")
pyttsx3.speak("Tell us about yourself")
about_me = input("tell us about yourself")
document.add_paragraph(about_me)

# company Details

pyttsx3.speak("enter your company")
company = input("enter your company")
pyttsx3.speak("enter joining date")
joining_date = input("enter joining date")
pyttsx3.speak("enter leaving date")
leaving_date = input("enter leaving date")
p = document.add_paragraph()
p.add_run(company + "\n ").bold = True
p.add_run("from " + joining_date + " to " + leaving_date).italic = True
pyttsx3.speak("enter your roll in " + company)
roll = input("enter your roll in " + company)
document.add_paragraph(roll)

# More Experience

while True:
    pyttsx3.speak("you have more experience : yes or no")
    exp = input("you have more experience : yes or no ")

    if (str(exp) == "yes"):
        pyttsx3.speak("enter your company")
        company = input("enter your company")
        pyttsx3.speak("enter joining date")
        joining_date = input("enter joining date")
        pyttsx3.speak("enter leaving date")
        leaving_date = input("enter leaving date")
        p = document.add_paragraph()
        p.add_run(company + "\n ").bold = True
        p.add_run("from " + joining_date + " to " + leaving_date).italic = True
        pyttsx3.speak("enter your roll in " + company)
        roll = input("enter your roll in " + company)
        document.add_paragraph(roll)
    else:
        break

# skills

pyttsx3.speak("enter your skills")
skill = input("enter your skills")
p = document.add_paragraph(skill)
p.style = "List Bullet"

# More Skills

while True:
    pyttsx3.speak("ypu have more skills : yes or no ")
    m_skill = input("ypu have more skills : yes or no  ")

    if (str(m_skill) == "yes"):
        pyttsx3.speak("enter your skills")
        skill = input("enter your skills")
        p = document.add_paragraph(skill)
        p.style = "List Bullet"
    else:
        break

# footer

section = document.sections[0]
footer = section.footer
p = footer.paragraphs[0]
p.text = " RESUME generated by Fayazz"

# Saving File

document.save("Resume.docx")
